use std::sync::LazyLock;

use crate::{Attribute, RoleFamily, RolePhase, RoleProfile};

#[derive(Clone, Copy)]
enum Archetype {
    Goalkeeper,
    BallPlayingGoalkeeper,
    SafeGoalkeeper,
    SweeperKeeper,
    LineKeeper,
    Defender,
    BallPlayingDefender,
    NoNonsenseDefender,
    Libero,
    OverlappingDefender,
    FullBack,
    WingBack,
    AdvancedWingBack,
    InvertedBack,
    PlaymakingWingBack,
    HoldingMidfielder,
    Playmaker,
    Runner,
    BallWinner,
    AttackingMidfielder,
    WideMidfielder,
    Winger,
    InsideForward,
    WideTarget,
    WideCreator,
    WideForward,
    LinkForward,
    GoalForward,
    TargetForward,
    CompleteForward,
    Pressing,
    Screening,
    Covering,
    Tracking,
    Outlet,
}

static BUILTIN_ROLES: LazyLock<Vec<RoleProfile>> = LazyLock::new(|| {
    let mut roles = in_possession_roles();
    roles.extend(out_of_possession_roles());
    roles
});

pub fn builtin_roles() -> &'static [RoleProfile] {
    BUILTIN_ROLES.as_slice()
}

pub fn in_possession_roles() -> Vec<RoleProfile> {
    use Archetype::*;
    use RoleFamily::{
        AttackingMidfield, CentralMidfield, CentreBack, DefensiveMidfield, Forward,
        FullBack as FullBackFamily, Goalkeeper as GoalkeeperFamily, WideMidfield,
        WingBack as WingBackFamily, Winger as WingerFamily,
    };
    use RolePhase::InPossession;
    vec![
        role(
            "goalkeeper",
            "Goalkeeper",
            InPossession,
            GoalkeeperFamily,
            Archetype::Goalkeeper,
        ),
        role(
            "ball_playing_goalkeeper",
            "Ball-Playing Goalkeeper",
            InPossession,
            GoalkeeperFamily,
            BallPlayingGoalkeeper,
        ),
        role(
            "no_nonsense_goalkeeper",
            "No-Nonsense Goalkeeper",
            InPossession,
            GoalkeeperFamily,
            SafeGoalkeeper,
        ),
        role(
            "full_back",
            "Full-Back",
            InPossession,
            FullBackFamily,
            Archetype::FullBack,
        ),
        role(
            "wing_back",
            "Wing-Back",
            InPossession,
            WingBackFamily,
            Archetype::WingBack,
        ),
        role(
            "no_nonsense_full_back",
            "No-Nonsense Full-Back",
            InPossession,
            FullBackFamily,
            NoNonsenseDefender,
        ),
        role(
            "advanced_wing_back",
            "Advanced Wing-Back",
            InPossession,
            WingBackFamily,
            AdvancedWingBack,
        ),
        role(
            "inside_wing_back",
            "Inside Wing-Back",
            InPossession,
            WingBackFamily,
            InvertedBack,
        ),
        role(
            "inside_full_back",
            "Inside Full-Back",
            InPossession,
            FullBackFamily,
            InvertedBack,
        ),
        role(
            "playmaking_wing_back",
            "Playmaking Wing-Back",
            InPossession,
            WingBackFamily,
            PlaymakingWingBack,
        ),
        role(
            "central_defender",
            "Central Defender",
            InPossession,
            CentreBack,
            Defender,
        ),
        role("libero", "Libero", InPossession, CentreBack, Libero),
        role(
            "ball_playing_defender",
            "Ball-Playing Defender",
            InPossession,
            CentreBack,
            BallPlayingDefender,
        ),
        role(
            "no_nonsense_centre_back",
            "No-Nonsense Centre-Back",
            InPossession,
            CentreBack,
            NoNonsenseDefender,
        ),
        role(
            "wide_centre_back",
            "Wide Centre-Back",
            InPossession,
            CentreBack,
            Archetype::FullBack,
        ),
        role(
            "overlapping_centre_back",
            "Overlapping Centre-Back",
            InPossession,
            CentreBack,
            OverlappingDefender,
        ),
        role(
            "midfield_playmaker",
            "Midfield Playmaker",
            InPossession,
            CentralMidfield,
            Playmaker,
        ),
        role(
            "defensive_midfielder",
            "Defensive Midfielder",
            InPossession,
            DefensiveMidfield,
            HoldingMidfielder,
        ),
        role(
            "central_midfielder",
            "Central Midfielder",
            InPossession,
            CentralMidfield,
            Runner,
        ),
        role(
            "deep_lying_playmaker",
            "Deep-Lying Playmaker",
            InPossession,
            DefensiveMidfield,
            Playmaker,
        ),
        role(
            "box_to_box_midfielder",
            "Box-to-Box Midfielder",
            InPossession,
            CentralMidfield,
            Runner,
        ),
        role(
            "ball_winning_midfielder",
            "Ball-Winning Midfielder",
            InPossession,
            CentralMidfield,
            BallWinner,
        ),
        role(
            "anchor",
            "Anchor",
            InPossession,
            DefensiveMidfield,
            HoldingMidfielder,
        ),
        role(
            "half_back",
            "Half-Back",
            InPossession,
            DefensiveMidfield,
            Defender,
        ),
        role(
            "regista",
            "Regista",
            InPossession,
            DefensiveMidfield,
            Playmaker,
        ),
        role(
            "box_to_box_playmaker",
            "Box-to-Box Playmaker",
            InPossession,
            CentralMidfield,
            Playmaker,
        ),
        role(
            "segundo_volante",
            "Segundo Volante",
            InPossession,
            DefensiveMidfield,
            Runner,
        ),
        role(
            "wide_midfielder",
            "Wide Midfielder",
            InPossession,
            WideMidfield,
            Archetype::WideMidfielder,
        ),
        role(
            "winger",
            "Winger",
            InPossession,
            WingerFamily,
            Archetype::Winger,
        ),
        role(
            "attacking_midfielder",
            "Attacking Midfielder",
            InPossession,
            AttackingMidfield,
            Archetype::AttackingMidfielder,
        ),
        role(
            "channel_midfielder",
            "Channel Midfielder",
            InPossession,
            AttackingMidfield,
            Runner,
        ),
        role(
            "advanced_playmaker",
            "Advanced Playmaker",
            InPossession,
            AttackingMidfield,
            Playmaker,
        ),
        role(
            "inside_forward",
            "Inside Forward",
            InPossession,
            WingerFamily,
            Archetype::InsideForward,
        ),
        role(
            "inverted_winger",
            "Inverted Winger",
            InPossession,
            WingerFamily,
            Archetype::InsideForward,
        ),
        role(
            "defensive_winger",
            "Defensive Winger",
            InPossession,
            WingerFamily,
            Pressing,
        ),
        role(
            "wide_target_forward",
            "Wide Target Forward",
            InPossession,
            WingerFamily,
            WideTarget,
        ),
        role(
            "wide_playmaker",
            "Wide Playmaker",
            InPossession,
            WideMidfield,
            WideCreator,
        ),
        role(
            "wide_forward",
            "Wide Forward",
            InPossession,
            WingerFamily,
            Archetype::WideForward,
        ),
        role(
            "wide_central_midfielder",
            "Wide Central Midfielder",
            InPossession,
            CentralMidfield,
            Archetype::WideMidfielder,
        ),
        role(
            "deep_lying_forward",
            "Deep-Lying Forward",
            InPossession,
            Forward,
            LinkForward,
        ),
        role(
            "centre_forward",
            "Centre Forward",
            InPossession,
            Forward,
            GoalForward,
        ),
        role(
            "target_forward",
            "Target Forward",
            InPossession,
            Forward,
            TargetForward,
        ),
        role("poacher", "Poacher", InPossession, Forward, GoalForward),
        role(
            "complete_forward",
            "Complete Forward",
            InPossession,
            Forward,
            CompleteForward,
        ),
        role(
            "channel_forward",
            "Channel Forward",
            InPossession,
            Forward,
            GoalForward,
        ),
        role(
            "false_nine",
            "False Nine",
            InPossession,
            Forward,
            LinkForward,
        ),
        role(
            "shadow_striker",
            "Shadow Striker",
            InPossession,
            AttackingMidfield,
            GoalForward,
        ),
    ]
}

pub fn out_of_possession_roles() -> Vec<RoleProfile> {
    use Archetype::*;
    use RoleFamily::{
        AttackingMidfield, CentralMidfield, CentreBack, DefensiveMidfield, Forward,
        FullBack as FullBackFamily, Goalkeeper as GoalkeeperFamily, WideMidfield,
        WingBack as WingBackFamily, Winger as WingerFamily,
    };
    use RolePhase::OutOfPossession;
    vec![
        role(
            "oop_goalkeeper",
            "Goalkeeper",
            OutOfPossession,
            GoalkeeperFamily,
            Archetype::Goalkeeper,
        ),
        role(
            "oop_sweeper_keeper",
            "Sweeper Keeper",
            OutOfPossession,
            GoalkeeperFamily,
            SweeperKeeper,
        ),
        role(
            "oop_line_keeper",
            "Line Keeper",
            OutOfPossession,
            GoalkeeperFamily,
            LineKeeper,
        ),
        role(
            "oop_centre_back",
            "Centre-Back",
            OutOfPossession,
            CentreBack,
            Defender,
        ),
        role(
            "oop_stopping_centre_back",
            "Stopping Centre-Back",
            OutOfPossession,
            CentreBack,
            Pressing,
        ),
        role(
            "oop_covering_centre_back",
            "Covering Centre-Back",
            OutOfPossession,
            CentreBack,
            Covering,
        ),
        role(
            "oop_wide_centre_back",
            "Wide Centre-Back",
            OutOfPossession,
            CentreBack,
            Archetype::FullBack,
        ),
        role(
            "oop_stopping_wide_centre_back",
            "Stopping Wide Centre-Back",
            OutOfPossession,
            CentreBack,
            Pressing,
        ),
        role(
            "oop_covering_wide_centre_back",
            "Covering Wide Centre-Back",
            OutOfPossession,
            CentreBack,
            Covering,
        ),
        role(
            "oop_full_back",
            "Full-Back",
            OutOfPossession,
            FullBackFamily,
            Archetype::FullBack,
        ),
        role(
            "oop_pressing_full_back",
            "Pressing Full-Back",
            OutOfPossession,
            FullBackFamily,
            Pressing,
        ),
        role(
            "oop_holding_full_back",
            "Holding Full-Back",
            OutOfPossession,
            FullBackFamily,
            Screening,
        ),
        role(
            "oop_wing_back",
            "Wing-Back",
            OutOfPossession,
            WingBackFamily,
            Archetype::WingBack,
        ),
        role(
            "oop_pressing_wing_back",
            "Pressing Wing-Back",
            OutOfPossession,
            WingBackFamily,
            Pressing,
        ),
        role(
            "oop_holding_wing_back",
            "Holding Wing-Back",
            OutOfPossession,
            WingBackFamily,
            Screening,
        ),
        role(
            "oop_defensive_midfielder",
            "Defensive Midfielder",
            OutOfPossession,
            DefensiveMidfield,
            HoldingMidfielder,
        ),
        role(
            "oop_dropping_defensive_midfielder",
            "Dropping Defensive Midfielder",
            OutOfPossession,
            DefensiveMidfield,
            Covering,
        ),
        role(
            "oop_pressing_defensive_midfielder",
            "Pressing Defensive Midfielder",
            OutOfPossession,
            DefensiveMidfield,
            Pressing,
        ),
        role(
            "oop_screening_defensive_midfielder",
            "Screening Defensive Midfielder",
            OutOfPossession,
            DefensiveMidfield,
            Screening,
        ),
        role(
            "oop_wide_cover_defensive_midfielder",
            "Wide Covering Defensive Midfielder",
            OutOfPossession,
            DefensiveMidfield,
            Covering,
        ),
        role(
            "oop_central_midfielder",
            "Central Midfielder",
            OutOfPossession,
            CentralMidfield,
            HoldingMidfielder,
        ),
        role(
            "oop_pressing_central_midfielder",
            "Pressing Central Midfielder",
            OutOfPossession,
            CentralMidfield,
            Pressing,
        ),
        role(
            "oop_screening_central_midfielder",
            "Screening Central Midfielder",
            OutOfPossession,
            CentralMidfield,
            Screening,
        ),
        role(
            "oop_wide_cover_central_midfielder",
            "Wide Covering Midfielder",
            OutOfPossession,
            CentralMidfield,
            Covering,
        ),
        role(
            "oop_attacking_midfielder",
            "Attacking Midfielder",
            OutOfPossession,
            AttackingMidfield,
            HoldingMidfielder,
        ),
        role(
            "oop_tracking_attacking_midfielder",
            "Tracking Attacking Midfielder",
            OutOfPossession,
            AttackingMidfield,
            Tracking,
        ),
        role(
            "oop_central_outlet_midfielder",
            "Central Outlet Midfielder",
            OutOfPossession,
            AttackingMidfield,
            Outlet,
        ),
        role(
            "oop_splitting_outlet_attacking_midfielder",
            "Splitting Outlet Attacking Midfielder",
            OutOfPossession,
            AttackingMidfield,
            Outlet,
        ),
        role(
            "oop_wide_midfielder",
            "Wide Midfielder",
            OutOfPossession,
            WideMidfield,
            HoldingMidfielder,
        ),
        role(
            "oop_tracking_wide_midfielder",
            "Tracking Wide Midfielder",
            OutOfPossession,
            WideMidfield,
            Tracking,
        ),
        role(
            "oop_wide_outlet_midfielder",
            "Wide Outlet Midfielder",
            OutOfPossession,
            WideMidfield,
            Outlet,
        ),
        role(
            "oop_winger",
            "Winger",
            OutOfPossession,
            WingerFamily,
            HoldingMidfielder,
        ),
        role(
            "oop_tracking_winger",
            "Tracking Winger",
            OutOfPossession,
            WingerFamily,
            Tracking,
        ),
        role(
            "oop_inverting_outlet_winger",
            "Inverting Outlet Winger",
            OutOfPossession,
            WingerFamily,
            Outlet,
        ),
        role(
            "oop_wide_outlet_winger",
            "Wide Outlet Winger",
            OutOfPossession,
            WingerFamily,
            Outlet,
        ),
        role(
            "oop_centre_forward",
            "Centre Forward",
            OutOfPossession,
            Forward,
            HoldingMidfielder,
        ),
        role(
            "oop_tracking_centre_forward",
            "Tracking Centre Forward",
            OutOfPossession,
            Forward,
            Tracking,
        ),
        role(
            "oop_central_outlet_forward",
            "Centre Outlet Forward",
            OutOfPossession,
            Forward,
            Outlet,
        ),
        role(
            "oop_splitting_outlet_forward",
            "Splitting Outlet Forward",
            OutOfPossession,
            Forward,
            Outlet,
        ),
    ]
}

fn role(
    id: &str,
    name: &str,
    phase: RolePhase,
    family: RoleFamily,
    archetype: Archetype,
) -> RoleProfile {
    RoleProfile {
        id: id.to_owned(),
        name: name.to_owned(),
        phase,
        family,
        weights: weights(archetype).iter().copied().collect(),
    }
}

fn weights(archetype: Archetype) -> &'static [(Attribute, f64)] {
    use Archetype::*;
    use Attribute::*;
    match archetype {
        Archetype::Goalkeeper => &[
            (Reflexes, 1.0),
            (Handling, 1.0),
            (OneOnOnes, 0.9),
            (CommandOfArea, 0.8),
            (Positioning, 0.9),
            (Concentration, 0.8),
            (Agility, 0.8),
        ],
        BallPlayingGoalkeeper => &[
            (Passing, 1.0),
            (Kicking, 1.0),
            (Throwing, 0.8),
            (FirstTouch, 0.9),
            (Composure, 0.9),
            (Decisions, 0.9),
            (Reflexes, 0.8),
            (Handling, 0.8),
        ],
        SafeGoalkeeper => &[
            (Handling, 1.0),
            (Reflexes, 1.0),
            (AerialReach, 0.9),
            (CommandOfArea, 0.9),
            (Communication, 0.8),
            (Concentration, 0.9),
            (Decisions, 0.8),
        ],
        SweeperKeeper => &[
            (RushingOutTendency, 1.0),
            (OneOnOnes, 1.0),
            (Acceleration, 0.8),
            (Pace, 0.8),
            (Anticipation, 0.9),
            (Decisions, 0.9),
            (Composure, 0.8),
            (Reflexes, 0.8),
        ],
        LineKeeper => &[
            (Reflexes, 1.0),
            (Handling, 1.0),
            (Positioning, 1.0),
            (Concentration, 0.9),
            (Agility, 0.9),
            (OneOnOnes, 0.8),
            (AerialReach, 0.7),
        ],
        Defender => &[
            (Marking, 1.0),
            (Tackling, 1.0),
            (Positioning, 1.0),
            (Heading, 0.8),
            (Anticipation, 0.9),
            (Concentration, 0.9),
            (Strength, 0.7),
            (JumpingReach, 0.7),
        ],
        BallPlayingDefender => &[
            (Marking, 0.9),
            (Tackling, 0.9),
            (Positioning, 0.9),
            (Anticipation, 0.9),
            (Passing, 1.0),
            (Technique, 0.8),
            (Composure, 1.0),
            (Vision, 0.8),
            (Decisions, 0.9),
        ],
        NoNonsenseDefender => &[
            (Marking, 1.0),
            (Tackling, 1.0),
            (Heading, 1.0),
            (Positioning, 1.0),
            (Strength, 0.9),
            (Bravery, 0.9),
            (Concentration, 0.9),
            (JumpingReach, 0.8),
        ],
        Libero => &[
            (Anticipation, 1.0),
            (Positioning, 0.9),
            (Passing, 1.0),
            (Vision, 0.9),
            (Technique, 0.8),
            (Composure, 0.9),
            (Decisions, 0.9),
            (Pace, 0.7),
        ],
        OverlappingDefender => &[
            (Marking, 0.8),
            (Tackling, 0.8),
            (Positioning, 0.8),
            (Stamina, 1.0),
            (WorkRate, 0.9),
            (OffTheBall, 0.8),
            (Crossing, 0.8),
            (Pace, 0.8),
        ],
        FullBack => &[
            (Marking, 0.9),
            (Tackling, 0.9),
            (Positioning, 0.9),
            (Stamina, 0.8),
            (WorkRate, 0.8),
            (Crossing, 0.7),
            (Acceleration, 0.7),
            (Decisions, 0.7),
        ],
        WingBack => &[
            (Crossing, 1.0),
            (Dribbling, 0.8),
            (Stamina, 1.0),
            (WorkRate, 0.9),
            (Acceleration, 0.9),
            (Pace, 0.9),
            (OffTheBall, 0.8),
            (Tackling, 0.6),
        ],
        AdvancedWingBack => &[
            (Crossing, 1.0),
            (Dribbling, 1.0),
            (Acceleration, 1.0),
            (Pace, 0.9),
            (OffTheBall, 0.9),
            (Stamina, 0.9),
            (Technique, 0.8),
            (Flair, 0.7),
        ],
        InvertedBack => &[
            (Passing, 1.0),
            (FirstTouch, 0.9),
            (Technique, 0.9),
            (Decisions, 1.0),
            (Positioning, 0.9),
            (Teamwork, 0.8),
            (Anticipation, 0.8),
            (Stamina, 0.7),
        ],
        PlaymakingWingBack => &[
            (Passing, 1.0),
            (Vision, 1.0),
            (Technique, 0.9),
            (FirstTouch, 0.9),
            (Crossing, 0.8),
            (Decisions, 0.9),
            (OffTheBall, 0.8),
            (Stamina, 0.7),
        ],
        HoldingMidfielder => &[
            (Positioning, 1.0),
            (Anticipation, 0.9),
            (Decisions, 0.9),
            (Concentration, 0.9),
            (Tackling, 0.8),
            (Marking, 0.8),
            (Teamwork, 0.8),
            (Strength, 0.6),
        ],
        Playmaker => &[
            (Passing, 1.0),
            (Vision, 1.0),
            (Decisions, 1.0),
            (FirstTouch, 0.9),
            (Technique, 0.9),
            (Composure, 0.8),
            (Teamwork, 0.6),
            (Anticipation, 0.6),
        ],
        Runner => &[
            (Stamina, 1.0),
            (WorkRate, 1.0),
            (OffTheBall, 0.9),
            (Anticipation, 0.8),
            (Acceleration, 0.8),
            (Teamwork, 0.8),
            (Decisions, 0.8),
            (Passing, 0.7),
        ],
        BallWinner => &[
            (Tackling, 1.0),
            (Aggression, 1.0),
            (Bravery, 0.9),
            (WorkRate, 1.0),
            (Stamina, 0.9),
            (Anticipation, 0.8),
            (Teamwork, 0.8),
            (Strength, 0.7),
        ],
        AttackingMidfielder => &[
            (FirstTouch, 1.0),
            (Technique, 1.0),
            (Passing, 0.9),
            (Vision, 0.9),
            (OffTheBall, 0.9),
            (Decisions, 0.8),
            (Dribbling, 0.8),
            (Finishing, 0.7),
        ],
        WideMidfielder => &[
            (Crossing, 0.9),
            (Passing, 0.8),
            (WorkRate, 0.9),
            (Stamina, 0.8),
            (Teamwork, 0.8),
            (OffTheBall, 0.7),
            (Technique, 0.7),
            (Decisions, 0.7),
        ],
        Winger => &[
            (Crossing, 1.0),
            (Dribbling, 1.0),
            (Acceleration, 1.0),
            (Pace, 1.0),
            (OffTheBall, 0.8),
            (Technique, 0.8),
            (Flair, 0.7),
            (Agility, 0.7),
        ],
        InsideForward => &[
            (Dribbling, 1.0),
            (Finishing, 1.0),
            (OffTheBall, 1.0),
            (Acceleration, 0.9),
            (Pace, 0.9),
            (Technique, 0.8),
            (FirstTouch, 0.8),
            (Composure, 0.8),
        ],
        WideTarget => &[
            (Heading, 1.0),
            (JumpingReach, 1.0),
            (Strength, 1.0),
            (FirstTouch, 0.8),
            (OffTheBall, 0.8),
            (Bravery, 0.8),
            (Teamwork, 0.7),
            (Finishing, 0.6),
        ],
        WideCreator => &[
            (Passing, 1.0),
            (Vision, 1.0),
            (Technique, 0.9),
            (FirstTouch, 0.9),
            (Crossing, 0.8),
            (Flair, 0.8),
            (Decisions, 0.9),
            (Composure, 0.7),
        ],
        WideForward => &[
            (Acceleration, 1.0),
            (Pace, 1.0),
            (Dribbling, 1.0),
            (OffTheBall, 0.9),
            (Finishing, 0.9),
            (Composure, 0.8),
            (Technique, 0.8),
            (FirstTouch, 0.7),
        ],
        LinkForward => &[
            (FirstTouch, 1.0),
            (Passing, 0.9),
            (Vision, 0.8),
            (Technique, 0.9),
            (Teamwork, 0.8),
            (OffTheBall, 0.8),
            (Composure, 0.8),
            (Strength, 0.6),
        ],
        GoalForward => &[
            (Finishing, 1.0),
            (OffTheBall, 1.0),
            (Composure, 1.0),
            (Acceleration, 0.9),
            (Anticipation, 0.9),
            (FirstTouch, 0.8),
            (Pace, 0.8),
            (Decisions, 0.7),
        ],
        TargetForward => &[
            (Heading, 1.0),
            (JumpingReach, 1.0),
            (Strength, 1.0),
            (Bravery, 0.9),
            (FirstTouch, 0.8),
            (OffTheBall, 0.7),
            (Teamwork, 0.8),
            (Finishing, 0.7),
        ],
        CompleteForward => &[
            (Finishing, 1.0),
            (FirstTouch, 0.9),
            (Technique, 0.9),
            (OffTheBall, 1.0),
            (Composure, 0.9),
            (Passing, 0.8),
            (Acceleration, 0.8),
            (Strength, 0.8),
            (Heading, 0.7),
        ],
        Pressing => &[
            (WorkRate, 1.0),
            (Stamina, 1.0),
            (Aggression, 0.9),
            (Anticipation, 0.9),
            (Teamwork, 0.9),
            (Tackling, 0.8),
            (Acceleration, 0.8),
            (Bravery, 0.7),
        ],
        Screening => &[
            (Positioning, 1.0),
            (Anticipation, 1.0),
            (Concentration, 0.9),
            (Decisions, 0.9),
            (Marking, 0.9),
            (Teamwork, 0.8),
            (Tackling, 0.8),
            (Strength, 0.6),
        ],
        Covering => &[
            (Positioning, 1.0),
            (Anticipation, 1.0),
            (Pace, 0.9),
            (Acceleration, 0.8),
            (Concentration, 0.9),
            (Decisions, 0.9),
            (Marking, 0.8),
            (Teamwork, 0.7),
        ],
        Tracking => &[
            (WorkRate, 1.0),
            (Stamina, 1.0),
            (Teamwork, 0.9),
            (Positioning, 0.8),
            (Marking, 0.8),
            (Anticipation, 0.8),
            (Acceleration, 0.8),
            (Tackling, 0.7),
        ],
        Outlet => &[
            (Acceleration, 1.0),
            (Pace, 1.0),
            (OffTheBall, 1.0),
            (Anticipation, 0.9),
            (FirstTouch, 0.8),
            (Dribbling, 0.8),
            (Composure, 0.8),
            (Decisions, 0.7),
        ],
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    #[test]
    fn covers_the_verified_fm26_two_phase_role_inventory() {
        let roles = builtin_roles();
        assert_eq!(in_possession_roles().len(), 47);
        assert_eq!(out_of_possession_roles().len(), 39);
        assert_eq!(roles.len(), 86);
        assert_eq!(
            roles
                .iter()
                .map(|role| role.id.as_str())
                .collect::<HashSet<_>>()
                .len(),
            roles.len()
        );
        assert!(roles.iter().all(|role| !role.weights.is_empty()));
        assert!(
            !roles
                .iter()
                .any(|role| matches!(role.name.as_str(), "Mezzala" | "Enganche" | "Trequartista"))
        );
    }

    #[test]
    fn every_attribute_weight_is_positive_and_finite() {
        for role in builtin_roles() {
            assert!(
                role.weights
                    .values()
                    .all(|weight| weight.is_finite() && *weight > 0.0),
                "{} contains an invalid weight",
                role.id
            );
        }
    }
}
